// Code generated by MockGen. DO NOT EDIT.
// Source: dbhandler/handler.go

// Package dbhandler is a generated GoMock package.
package dbhandler

import (
	models "UserStorage/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBHandler is a mock of DBHandler interface.
type MockDBHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDBHandlerMockRecorder
}

// MockDBHandlerMockRecorder is the mock recorder for MockDBHandler.
type MockDBHandlerMockRecorder struct {
	mock *MockDBHandler
}

// NewMockDBHandler creates a new mock instance.
func NewMockDBHandler(ctrl *gomock.Controller) *MockDBHandler {
	mock := &MockDBHandler{ctrl: ctrl}
	mock.recorder = &MockDBHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBHandler) EXPECT() *MockDBHandlerMockRecorder {
	return m.recorder
}

// AddFileToUser mocks base method.
func (m *MockDBHandler) AddFileToUser(ctx context.Context, id string, file models.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFileToUser", ctx, id, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFileToUser indicates an expected call of AddFileToUser.
func (mr *MockDBHandlerMockRecorder) AddFileToUser(ctx, id, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFileToUser", reflect.TypeOf((*MockDBHandler)(nil).AddFileToUser), ctx, id, file)
}

// CreateUser mocks base method.
func (m *MockDBHandler) CreateUser(ctx context.Context, usr models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, usr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDBHandlerMockRecorder) CreateUser(ctx, usr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDBHandler)(nil).CreateUser), ctx, usr)
}

// DeleteFilesFromUser mocks base method.
func (m *MockDBHandler) DeleteFilesFromUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFilesFromUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFilesFromUser indicates an expected call of DeleteFilesFromUser.
func (mr *MockDBHandlerMockRecorder) DeleteFilesFromUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFilesFromUser", reflect.TypeOf((*MockDBHandler)(nil).DeleteFilesFromUser), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockDBHandler) DeleteUser(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockDBHandlerMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockDBHandler)(nil).DeleteUser), ctx, id)
}

// GetUser mocks base method.
func (m *MockDBHandler) GetUser(ctx context.Context, id string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockDBHandlerMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDBHandler)(nil).GetUser), ctx, id)
}

// GetUserFiles mocks base method.
func (m *MockDBHandler) GetUserFiles(ctx context.Context, id string) ([]models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFiles", ctx, id)
	ret0, _ := ret[0].([]models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFiles indicates an expected call of GetUserFiles.
func (mr *MockDBHandlerMockRecorder) GetUserFiles(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFiles", reflect.TypeOf((*MockDBHandler)(nil).GetUserFiles), ctx, id)
}

// GetUsers mocks base method.
func (m *MockDBHandler) GetUsers(ctx context.Context) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockDBHandlerMockRecorder) GetUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockDBHandler)(nil).GetUsers), ctx)
}

// UpdateUser mocks base method.
func (m *MockDBHandler) UpdateUser(ctx context.Context, usr models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, usr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockDBHandlerMockRecorder) UpdateUser(ctx, usr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockDBHandler)(nil).UpdateUser), ctx, usr)
}
