// Code generated by MockGen. DO NOT EDIT.
// Source: queueHandler/queueHandler.go

// Package queueHandler_test is a generated GoMock package.
package queueHandler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQueueHandler is a mock of QueueHandler interface.
type MockQueueHandler struct {
	ctrl     *gomock.Controller
	recorder *MockQueueHandlerMockRecorder
}

// MockQueueHandlerMockRecorder is the mock recorder for MockQueueHandler.
type MockQueueHandlerMockRecorder struct {
	mock *MockQueueHandler
}

// NewMockQueueHandler creates a new mock instance.
func NewMockQueueHandler(ctrl *gomock.Controller) *MockQueueHandler {
	mock := &MockQueueHandler{ctrl: ctrl}
	mock.recorder = &MockQueueHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueHandler) EXPECT() *MockQueueHandlerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockQueueHandler) Publish(ev any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ev)
}

// Publish indicates an expected call of Publish.
func (mr *MockQueueHandlerMockRecorder) Publish(ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockQueueHandler)(nil).Publish), ev)
}
